version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/setup-laravel
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: ci
