name: tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    uses: datalogix/workflows/.github/workflows/laravel-app-tests.yml@v1
    # All inputs are optional:
    # with:
    #   php-version: "8.3"
    #   pint: false
    #   phpstan: false
